export const contacts = [
    {
      id: "1",
      firstName: "Colleen",
      lastName: "Mosses",
      avatar: "https://randomuser.me/api/portraits/women/1.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Today",
    },
    {
      id: "2",
      firstName: "Max",
      lastName: "Bennett",
      avatar: "https://randomuser.me/api/portraits/men/2.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Today",
    },
    {
      id: "3",
      firstName: "Soham",
      lastName: "Miles",
      avatar: "https://randomuser.me/api/portraits/men/3.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Today",
    },
    {
      id: "4",
      firstName: "Kristin",
      lastName: "Watson",
      avatar: "https://randomuser.me/api/portraits/women/4.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Today",
    },
    {
      id: "5",
      firstName: "Eduardo",
      lastName: "Miles",
      avatar: "https://randomuser.me/api/portraits/men/5.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Yesterday",
    },
    {
      id: "6",
      firstName: "Dianne",
      lastName: "Marshall",
      avatar: "https://randomuser.me/api/portraits/women/6.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Yesterday",
    },
    {
      id: "7",
      firstName: "Arlene",
      lastName: "Young",
      avatar: "https://randomuser.me/api/portraits/women/7.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Yesterday",
    },
    {
      id: "8",
      firstName: "Shane",
      lastName: "Hudson",
      avatar: "https://randomuser.me/api/portraits/men/8.jpg",
      lastMessage: "As-salamu alaykum, Leslie!...",
      time: "Yesterday",
    },
  ];
  